### ISSUE TITLE
torchgeometry collaboration

### ISSUE THREAD

**Issue by edgarriba** [jeanfeydy/geomloss#1]
Hi, I'm the author of PyTorch Geometry and I would like to discuss with you potential collaborations between packages. We already have a defined losses module which we would like to expand with your stuff. We have a consolidated testing framework and supporting cuda pretty soon in our contiguous integration pipeline. I couldn't find any email contact. Please, try to reach me out.

**Comment by jeanfeydy** [comment]
Dear Edgar,
All my apologies for the long delay: these last few weeks, I've been really focusing on the AiStats conference and the v1.0 release of the [KeOps library](www.kernel-operations.io), without much time to support GeomLoss - which is still in alpha.
I now plan to work towards a full stable release: if you're still interested in the discussion, feel free to contact me at jean.feydy@ens.fr :-)

Best regards,
Jean
