### ISSUE TITLE
tensor shape dismatched when computing batch sinkhorn loss

### ISSUE THREAD

**Issue by heslowen** [jeanfeydy/geomloss#11]
when I try to compute the loss of a batch data, I met this bug.
```python
import torch
from geomloss import SamplesLoss  # See also ImagesLoss, VolumesLoss
cuda_device = torch.device("cuda:%d" % 0 if torch.cuda.is_available() else "cpu")
x=torch.randn(100,90,400, requires_grad=True).to(cuda_device)
y=torch.randn(100,90,400).to(cuda_device)
# Define a Sinkhorn (~Wasserstein) loss between sampled measures
loss = SamplesLoss(loss="sinkhorn", p=2, blur=.05)
L = loss(x, y)  # By default, use constant weights = 1/number of samples
print(L.item())
g_x, = torch.autograd.grad(L, [x])  # GeomLoss fully supports autograd!
print(g_x)
```
output
```python
Traceback (most recent call last):
  File "/home/lowen/program/pycharm-community-2018.2.3/helpers/pydev/pydevd.py", line 1664, in <module>
    main()
  File "/home/lowen/program/pycharm-community-2018.2.3/helpers/pydev/pydevd.py", line 1658, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/home/lowen/program/pycharm-community-2018.2.3/helpers/pydev/pydevd.py", line 1068, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/home/lowen/program/pycharm-community-2018.2.3/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/devdata/new_Relation_Extraction/test_geomloss.py", line 40, in <module>
    L = loss(x, y)  # By default, use constant weights = 1/number of samples
  File "/home/lowen/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/lowen/anaconda3/envs/pytorch/lib/python3.7/site-packages/geomloss/samples_loss.py", line 239, in forward
    verbose=self.verbose)
  File "/home/lowen/anaconda3/envs/pytorch/lib/python3.7/site-packages/geomloss/sinkhorn_samples.py", line 52, in sinkhorn_tensorized
    C_xx, C_yy, C_xy, C_yx, ε_s, ρ, debias=debias )
  File "/home/lowen/anaconda3/envs/pytorch/lib/python3.7/site-packages/geomloss/sinkhorn_divergence.py", line 162, in sinkhorn_loop
    at_x = λ * softmin(ε, C_xx, α_log + a_x/ε )  # OT(α,α)
RuntimeError: The size of tensor a (90) must match the size of tensor b (9000) at non-singleton dimension 1
```
So I debug the code and found that **a_x**([9000] tensors) dismatched **α_log** ([100,90] tensors), then I try to apply a view() operation to α_log just like this
```python
at_x = λ * softmin(ε, C_xx, α_log + (a_x / ε).view(α_log.size()))
```

After I fixed all this kind of bugs with a view() operation, it successfully returns a batch loss(in my case, that's [100] tensors).

**So I was wondering is it the right way to fix the bug?** or there is a batter way to compute wasserstein loss for a batch data?

Thx!!!

**Comment by jeanfeydy** [comment]
Hi @heslowen ,
Indeed!
In fact, I pushed this fix to master just three days ago in #9 : it is not yet available on PyPi, but will be up soon :-)
Best regards,
Jean

**Comment by heslowen** [comment]
@jeanfeydy Could you please tell that for batch data x and y (e.g. both [100,30,300] tensors), if I don't reduce the loss([100] tensor) to a scalar, is loss[0] corresponding to x[0] and y[:]?

**Comment by heslowen** [comment]
@jeanfeydy  Do you have a plan to optimize the computation for sparse α and β? ✧(•̀ω•́ )
```python
    def process_args(self, *args):
        if len(args) == 6:
            return args
        if len(args) == 4:
            α, x, β, y = args
            return None, α, x, None, β, y
        elif len(args) == 2:
            x, y = args
            α = self.generate_weights(x)
            β = self.generate_weights(y)
            return None, α, x, None, β, y
        else:
            raise ValueError(
                "A SamplesLoss accepts two (x, y), four (α, x, β, y) or six (l_x, α, x, l_y, β, y)  arguments.")
```
For example, α and β are [80000] tensors but only 100 elements are not zero！

**Comment by jeanfeydy** [comment]
Hi @heslowen ,

To answer your first question:
```python
x = torch.randn(100,90,400, requires_grad=True).to(cuda_device)
y = torch.randn(100,90,400).to(cuda_device)
# Define a Sinkhorn (~Wasserstein) loss between sampled measures
loss = SamplesLoss(loss="sinkhorn", p=2, blur=.05)
L = loss(x, y)  # By default, use constant weights = 1/number of samples
```
describes the computation of 100 pairwise (de-biased) Sinkhorn divergences `L[i] = S(x[i], y[i])` between clouds of 90 points in dimension 400.

As for sparse measures: sure, that's the whole point of SamplesLoss! 
In non-batch mode, a code along the lines of:
```python
mask_a = (a > 0)
a, x = a[mask_a].contiguous(), x[mask_a, :].contiguous()

mask_b = (b > 0)
b, y = b[mask_b].contiguous(), y[mask_b, :].contiguous()

L = loss(a, x, b, y)
```
allows you to filter the weightless particles before calling the GeomLoss solvers.
In batch mode, if you can represent your measures using a standard number of weighted particles (e.g. 100 atoms per measure, some of them having possibly null weights), the computation is straightforward using the current version of GeomLoss.
Long term, I will also add support for heterogeneous collections of measures with e.g. consecutive lengths `[100, 400, 30, ...]`. This is important for mesh processing, and relatively easy to do with KeOps's [Block-Sparse engine](https://www.kernel-operations.io/keops/python/sparsity.html). But as explained in e.g. [the documentation of PyTorch_Geometric](https://pytorch-geometric.readthedocs.io/en/latest/notes/introduction.html#mini-batches), this requires a non-trivial extension of the user interface: I'd rather wait a little bit and get to know the common practices in the field before supporting the feature officially.

**Comment by heslowen** [comment]
@jeanfeydy Good job！Thanks！!

**Comment by jeanfeydy** [comment]
You're welcome :-)
