### ISSUE TITLE
How to create a computation graph on tensorboardx?

### ISSUE THREAD

**Issue by heslowen** [jeanfeydy/geomloss#21]
Hello! Thanks for your work again!

I want to see the computation graph on tensorboradx but it seems impossible because there are many "if" statements. So I was wondering that had you visualized the computation graph when computing Wasserstein loss?

**Comment by jeanfeydy** [comment]
Hi @heslowen ,

You're welcome, and sorry for the late reply!
The computation graph of the [multiscale Sinkhorn solver](https://github.com/jeanfeydy/geomloss/blob/4e09e3bfd376d92f2bb7efdf0854a5b7c756eb0d/geomloss/sinkhorn_divergence.py#L126) should be pretty straightforward, as it's little more than a big "for" loop with an extrapolation step when necessary. What I find personally more interesting is the Chrome trace given as the output of [this tutorial](https://www.kernel-operations.io/geomloss/_auto_examples/performances/plot_profile.html).
It allows you to track the time spent for each instruction, and clearly spot that most of it is used in the last few iterations, at full resolution. 

Is this good enough for you? I'm closing the issue for the moment... but if you have  something more specific in mind, feel free to tell me so!

Best regards,
Jean
