### ISSUE TITLE
Make reach depend on diameter

### ISSUE THREAD

**Issue by AdrienCorenflos** [jeanfeydy/geomloss#23]
Hi,

Wouldn't it be better to have the reach param depend on the diameter of the data? It's probably easier to think of saturation of the distance in terms of %diameter than it is in the direct unit of the distance. What do you think?

**Comment by jeanfeydy** [comment]
HI @AdrienCorenflos ,

Sorry for the late reply, and thanks for your remark!
It would make sense, indeed, and this is how I always discuss entropic regularization in papers and talks. However, as far as the library is concerned, we should remember that the diameter of the (source + target) configuration typically changes between calls. 
In the context of optimization for geometry processing and machine learning, the current interface is thus much safer: it specifies a well-defined loss function that should (hopefully!) decrease across iterations. Changing it would leave the door open to confusions, for little benefit I think.

Best regards,
Jean
