### ISSUE TITLE
Batch training not support

### ISSUE THREAD

**Issue by wzm2256** [jeanfeydy/geomloss#26]
Test code 
```
import torch
from geomloss import SamplesLoss

A = torch.randn((5, 100, 1))
B = torch.randn((5, 100, 1))

L_ab = SamplesLoss('sinkhorn', p=1, blur=0.1, reach=None, debias=True, potentials=True, backend='tensorized')

f, g = L_ab(A, B)

C = A[0]
D = B[0]

h, i = L_ab(C, D)

a1 = f[0] - torch.mean(f[0])
a2 = h - torch.mean(h)

err = torch.norm(a1 - a2) / torch.norm(a2)

print(err)
```

Currently an error is thrown.

```
RuntimeError: The size of tensor a (100) must match the size of tensor b (500) at non-singleton dimension 1
```

After debugging a little bit.
The problem seems to be in sinkhorn_samples.py line 33, where the batch is not treated properly.
The problme is resolved when replacing line 33 by
```
return - ε * ( f.view(B,1,-1) - C/ε ).logsumexp(2).view(B, -1)
```
And the output now are like
```
tensor(0.0048)
```
which is reasonable to me.

What do you think?

**Comment by btrx-kheyer** [comment]
I'm also interested in batch training with SamplesLoss. I'm curious about the warning that the online backend does not support batched computation. Is this a fundamental limitation of KeOps or is there a way (at least in theory) to run online batch computation of SamplesLoss?

**Comment by jeanfeydy** [comment]
Woops, I had skipped this issue, sorry about that @wzm2256 !

To answer your question and @btrx-kheyer : no, batch computation with KeOps is fully on the cards. Over the last few months, I have mostly focused on writing math papers and improving KeOps with the "new" `LazyTensor` syntax. As these tasks have been mostly completed, I am now pivoting back to improving `GeomLoss` - and releasing a fully operational `v1.0`: we are currently refactoring all the code with @thibsej and @PierreRoussillon to include a wider support of unbalanced OT, batch processing, arbitrary cost functions and meshes :-)

Best regards,

Jean

**Comment by wzm2256** [comment]
Nice to hear there will be a v1.0 version :)   @jeanfeydy . Currently I'm working on a project based on the current version of geomloss. So far, I've made several modifications for more specific uses. I will make it public when the project is done, and you can check whether it is appropriate to merge these modifications to your code. :)
