### ISSUE TITLE
Looking forward to updating

### ISSUE THREAD

**Issue by JunMa11** [jeanfeydy/geomloss#30]
Dear @jeanfeydy ,

Thanks for your great. When will be the next update? e.g., out-of-the-box ImageLoss and VolumeLoss layers

![image](https://user-images.githubusercontent.com/19947331/83827364-c1258b80-a710-11ea-8c4e-2138ebd289c9.png)

Looking forward to updating.

Kindest regards,
Jun

**Comment by jeanfeydy** [comment]
Hi @JunMa11 ,

Thanks for your interest in the library!
All my apologies about this very long delay: I am currently getting back to active development on GeomLoss, and will update the package over the summer. The reasons for this lull in the development are threefold:

1. We've made crucial progress on the low-level engine of GeomLoss: the [KeOps](http://www.kernel-operations.io/) library. The introduction of the `LazyTensor` syntax is a game-changer for us: working with **symbolic tensors** is much more convenient than defining KeOps formulas by hand. On the other hand, implementing and documenting these new features diverted me from higher-level work on optimal transport theory.

2. I invested a considerable amount of time in writing my PhD thesis as an **accessible textbook** for newcomers in the field. I defended my PhD two weeks ago: the [thesis](http://www.jeanfeydy.com/geometric_data_analysis.pdf) and [slides](http://www.jeanfeydy.com/geometric_data_analysis_slides.pdf) are now freely available online. Feel free to check them for an introduction to geometric data analysis, and a discussion of future developments in computational optimal transport and shape analysis.

3. Finally, on a personal level, my relocation from Paris to London (at Imperial College) and the Covid crisis caused a significant amount of disruption.


Fortunately, this preliminary work is now close to completion. I will soon upgrade the GeomLoss website with material taken from my [PhD thesis](http://www.jeanfeydy.com/geometric_data_analysis.pdf), and implement the following features:

1. I will re-write the core routines of GeomLoss to rely on KeOps `LazyTensors`. This will allow users to work with arbitrary cost functions, beyond Euclidean distances: hyperbolic or Newton-like costs may be of special interest in e.g. machine learning and physics.

2. Full support for [unbalanced OT](https://arxiv.org/pdf/1910.12958.pdf), beyond the simple case of the Kullback-Leibler penalty. This is done in collaboration with @thibsej.

3. Actual support for meshes, with orientation- and curvature-aware loss functions. This is done in collaboration with @PierreRoussillon.

4. Better support for situations where the cost matrix is given as a large dense tensor, especially with respect to the memory footprint. This will be of interest for e.g. applications to genomics.

5. Truly efficient support for optimal transport on grids, i.e. images and volumes, with FFT-based schemes. The main bottleneck here is numerical precision: I will have to implement by hand a CUDA routine for 1D FFT in the log-domain. 

6. Efficient support for [Wasserstein barycenters](https://www.kernel-operations.io/geomloss/_auto_examples/optimal_transport/plot_wasserstein_barycenters_2D.html), with a clean "black-box" interface.


These points are discussed in depth in my thesis: we now have working prototypes for all of them... But packaging and documenting things comprehensively takes time! I hope to have a presentable v1.0 release by December: we'll see :-)

Best regards,
Jean

**Comment by JunMa11** [comment]
Hi @jeanfeydy ,

> I defended my PhD two weeks ago: the thesis and slides are now freely available online.

Congrats! 

I very enjoy reading your thesis and slides. You really did an awesome job during PhD.
Are you interested in recording a video to present your slides? It would be a great start for beginners (besides the thesis).

Also, looking forward to the following update.

Kindest regards,
Jun
