### ISSUE TITLE
Cannot access author's homepage with the mathy documents

### ISSUE THREAD

**Issue by odedbd** [jeanfeydy/geomloss#4]
Hi,

I've tried following the links in the Matchs and algorithms section of the docs, and I am getting an Apache server error 404 for the author's website at the ENS.

For example, the [link to the gradients flow tutorial](https://www.math.ens.fr/~feydy/Teaching/DataScience/gradient_flows.html).

Thanks,

**Comment by jeanfeydy** [comment]
Hi @odedbd ,

Looks like it was just a server-side problem at the ENS (these things happen from times to times): as far as I can tell, the link is up and running.

Best regards,
Jean
