### ISSUE TITLE
How to set GPU ID?

### ISSUE THREAD

**Issue by raywzy** [jeanfeydy/geomloss#5]
Very great package! My question is how to set the gpu device?

**Comment by jeanfeydy** [comment]
Hi @raywzy ,
Thanks!
I have very little experience with multi-GPU configurations, but GeomLoss should run smoothly with the standard PyTorch interface:
```python
gpuids = [0,1] if torch.cuda.device_count() > 1 else [0]
for gpuid in gpuids:
    with torch.cuda.device(gpuid):
        # Create your data on the gpu with .cuda(), work with GeomLoss, etc.
```
There is a [short tutorial](http://www.kernel-operations.io/keops/_auto_examples/pytorch/plot_gpu_select_example.html#tests-with-the-pytorch-api) on the subject in the KeOps documentation. I cannot try it right now, but would expect GeomLoss to handle this transparently. 
Does it work on your machine?

Best regards,
Jean

**Comment by raywzy** [comment]
@jeanfeydy   That works fine for me. Thanks a lot :D

**Comment by jeanfeydy** [comment]
You're welcome :-)
