### ISSUE TITLE
 name 'generic_logsumexp' is not defined

### ISSUE THREAD

**Issue by Qin-ai** [jeanfeydy/geomloss#52]
name 'generic_logsumexp' is not defined
```
a = torch.rand(28996, 2)
b = torch.rand(28996, 2)

samplesloss = SamplesLoss('sinkhorn')
samplesloss(a, b)
```

**Comment by Qin-ai** [comment]
!pip install pykeops

**Comment by Qin-ai** [comment]
`!pip install geomloss[full]`
must in google Coblab, it is not useful in Kaggle

**Comment by Qin-ai** [comment]
To install GeomLoss and all its (optional) dependencies, please:
        1 Install the CUDA toolkit, including the nvcc compiler.
        2 Install PyTorch.
        3 Install the KeOps library.
        4 Install GeomLoss with:`pip install geomloss`

**Comment by bigian98** [comment]
Hi FieeFLip, I noticed that this warning message appears to me only when the size of a and b is greater than a certain value; any suggestions?
