### ISSUE TITLE
Cite geomloss

### ISSUE THREAD

**Issue by kilianFatras** [jeanfeydy/geomloss#7]
Hello Jean !

Thanks for your amazing work ! I wonder how I should cite your geomloss framework. Do  you have a paper ? Or will you intend to have one soon ? 

Thanks again,

Best,

Kilian

**Comment by jeanfeydy** [comment]
Hi @kilianFatras ,

Thanks :-)
As of today, the best pointer is probably our AiStats2019 paper : 

```
@inproceedings{feydy2019interpolating,
  title={Interpolating between Optimal Transport and MMD using Sinkhorn Divergences},
  author={Feydy, Jean and S{\'e}journ{\'e}, Thibault and Vialard, Fran{\c{c}}ois-Xavier and Amari, Shun-ichi and Trouve, Alain and Peyr{\'e}, Gabriel},
  booktitle={The 22nd International Conference on Artificial Intelligence and Statistics},
  pages={2681--2690},
  year={2019}
}
```
I will probably work on getting a proper "1.0" version + journal paper out for 2020 with @PierreRoussillon and other colleagues, but there's still quite a long way to go I think!

Best regards,

Jean

**Comment by kilianFatras** [comment]
Perfect ! Thanks !
